- name: Install Apache
  apt:
    name:
      - php8.3-cli
      - php8.3-common
      - php8.3-mysql
      - php8.3-pdo
      - php8.3-mbstring
      - php8.3-imap
      - php8.3-curl
      - php8.3-intl
      - php8.3-xml
      - libapache2-mod-php8.3
      - php-zip
    state: present
    update_cache: yes

- name: Enable Apache rewrite module
  command: a2enmod rewrite
  notify: restart apache

- name: Copy PostfixAdmin vhost config
  template:
    src: postfixadmin.conf.j2
    dest: /etc/apache2/sites-available/postfixadmin.conf
  notify: restart apache

- name: Enable PostfixAdmin site
  command: a2ensite postfixadmin.conf
  notify: restart apache

- name: Ensure templates_c directory exists
  file:
    path: /var/www/postfixadmin/templates_c
    state: directory
    mode: "0755"
    owner: www-data
    group: www-data

- name: Set correct permissions for templates_c
  file:
    path: /var/www/postfixadmin/templates_c
    mode: "0755"
    recurse: yes
